# Content
pages_list:       
  "Home": '/'
  "Semantic Specification": '/spec'
  "Per-Platform APIs": '/apis'
  "Implementing OpenTracing": '/implementors'
  "Contributors": '/contributors'

# Dependencies
markdown:         redcarpet
highlighter:      pygments

redcarpet:
  extensions: 
    - autolink
    - with_toc_data

gems: 
  - jekyll-paginate
  - jekyll-gist
  - jekyll-mentions
  - jekyll-coffeescript

#paginate_path: "page:num"
#paginate:         5

# Permalinks
permalink:        pretty

# Setup
title:            The OpenTracing Project
tagline:          'Consistent, expressive, vendor-neutral APIs for distributed tracing and context propagation'
description:      'Consistent, expressive, vendor-neutral APIs for distributed tracing and context propagation'
url:              http://opentracing.io
baseurl:          /

author:
  name:           'The OpenTracing Authors'
  url:            http://opentracing.io

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/opentracing
