# Content
pages_list:       
  Home: '/'
  APIs: '/apis'
  Terminology: '/terminology'

# Dependencies
markdown:         redcarpet
highlighter:      pygments

redcarpet:
  extensions: 
    - autolink
    - with_toc_data

gems: 
  - jekyll-paginate
  - jekyll-gist
  - jekyll-mentions

#paginate_path: "page:num"
#paginate:         5

# Permalinks
permalink:        pretty

# Setup
title:            The OpenTracing Project
tagline:          'Common APIs for distributed tracing and context propagation'
description:      'Common APIs for distributed tracing and context propagation'
url:              http://opentracing.io
baseurl:          /

author:
  name:           'The OpenTracing Authors'
  url:            http://opentracing.io

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/opentracing
