permalink: pretty
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false
highlighter: rouge
url: //reimertz.github.io/opentracing.github.io
exclude: ['node_modules']
